//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17379
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNAS.Framework4.Security.Properties
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HNAS.Framework4.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization Rule Expression 的本地化字符串。
        /// </summary>
        internal static string AddAuthorizationRuleData {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add an authorization rule expression that defines when the rule takes effect. 的本地化字符串。
        /// </summary>
        internal static string AddAuthorizationRuleDataDescription {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization Rule 的本地化字符串。
        /// </summary>
        internal static string AddAuthorizationRuleProviderData {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds a new Authorization Rule provider. 的本地化字符串。
        /// </summary>
        internal static string AddAuthorizationRuleProviderDataDescription {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string AddCustomAuthorizationProviderData {
            get {
                return ResourceManager.GetString("AddCustomAuthorizationProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a custom authorization provider by selecting its type. 的本地化字符串。
        /// </summary>
        internal static string AddCustomAuthorizationProviderDataDescription {
            get {
                return ResourceManager.GetString("AddCustomAuthorizationProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization Requests Denied/sec is the rate at which authorization requests where denied. 的本地化字符串。
        /// </summary>
        internal static string AuthorizationCheckFailedHelpResource {
            get {
                return ResourceManager.GetString("AuthorizationCheckFailedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization Requests/sec is the rate at which authorization requests were received. 的本地化字符串。
        /// </summary>
        internal static string AuthorizationCheckPerformedHelpResource {
            get {
                return ResourceManager.GetString("AuthorizationCheckPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization failed 的本地化字符串。
        /// </summary>
        internal static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization 的本地化字符串。
        /// </summary>
        internal static string AuthorizationProvidersDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationProvidersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization rule {0} not found in configuration. 的本地化字符串。
        /// </summary>
        internal static string AuthorizationRuleNotFoundMsg {
            get {
                return ResourceManager.GetString("AuthorizationRuleNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 curity Application Block 的本地化字符串。
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The error occurred retrieving the configuration for authorization provider instance &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorAuthorizationConfigurationFailedMessage {
            get {
                return ResourceManager.GetString("ErrorAuthorizationConfigurationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The error occurred retrieving the configuration for security cache provider instance &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorSecurityCacheConfigurationFailedMessage {
            get {
                return ResourceManager.GetString("ErrorSecurityCacheConfigurationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The authentication provider named &apos;{0}&apos; could not be found in configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAuthenticationProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The authorization provider named &apos;{0}&apos; could not be found in configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAuthorizationProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionAuthorizationProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must be implemented by subclasses. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMustBeImplementedBySubclass {
            get {
                return ResourceManager.GetString("ExceptionMustBeImplementedBySubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter must implement type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExceptionParameterMustImplementType {
            get {
                return ResourceManager.GetString("ExceptionParameterMustImplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The profile provider named &apos;{0}&apos; could not be found in configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionProfileProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionProfileProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The roles provider named &apos;{0}&apos; could not be found in configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionRolesProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionRolesProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The security cache provider named &apos;{0}&apos; could not be found in configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionSecurityCacheProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionSecurityCacheProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Custom Authentication Provider &apos;{0}&apos; with Type &apos;{1}&apos; must derive from IAuthorizationProvider 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeForCustomAuthProviderMustDeriveFrom {
            get {
                return ResourceManager.GetString("ExceptionTypeForCustomAuthProviderMustDeriveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Custom Security Cache Provider &apos;{0}&apos; with Type &apos;{1}&apos; must derive from ISecurityCacheProvider 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeForCustomCacheProviderMustDeriveFrom {
            get {
                return ResourceManager.GetString("ExceptionTypeForCustomCacheProviderMustDeriveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided IIdentity object is incomplete or invalid. 的本地化字符串。
        /// </summary>
        internal static string IdentityInvalid {
            get {
                return ResourceManager.GetString("IdentityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided IIdentity object is null. 的本地化字符串。
        /// </summary>
        internal static string IdentityIsNull {
            get {
                return ResourceManager.GetString("IdentityIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert，create，select，delete，script，|，;，$，%，&apos;，\&apos;，&amp;lt;，&amp;gt;，CR，LF，\，/*，*/ 的本地化字符串。
        /// </summary>
        internal static string IllegalChars {
            get {
                return ResourceManager.GetString("IllegalChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update，drop，and，exec，count，chr，mid，master，or，truncate，char，declare，join 的本地化字符串。
        /// </summary>
        internal static string IllegalSQLKeys {
            get {
                return ResourceManager.GetString("IllegalSQLKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &quot;securityConfiguration&quot; section is not available in the supplied configuration source. 的本地化字符串。
        /// </summary>
        internal static string MissingSection {
            get {
                return ResourceManager.GetString("MissingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no default authorization provider defined in the &quot;securityConfiguration&quot; section available in the supplied configuration source. 的本地化字符串。
        /// </summary>
        internal static string NoDefaultAuthorizationProvider {
            get {
                return ResourceManager.GetString("NoDefaultAuthorizationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no default security cache provider defined in the &quot;securityConfiguration&quot; section available in the supplied configuration source. 的本地化字符串。
        /// </summary>
        internal static string NoDefaultSecurityCacheProvider {
            get {
                return ResourceManager.GetString("NoDefaultSecurityCacheProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security Cache 的本地化字符串。
        /// </summary>
        internal static string SecurityCacheProvidersDisplayName {
            get {
                return ResourceManager.GetString("SecurityCacheProvidersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security Cache Reads/sec is the rate at which security cache reads were requested. 的本地化字符串。
        /// </summary>
        internal static string SecurityCacheReadPerformedHelpResource {
            get {
                return ResourceManager.GetString("SecurityCacheReadPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security Application Block 的本地化字符串。
        /// </summary>
        internal static string SecuritySettingsDisplayName {
            get {
                return ResourceManager.GetString("SecuritySettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Authorization Requests Denied is the total number of authorization requests denied. 的本地化字符串。
        /// </summary>
        internal static string TotalAuthorizationCheckFailedHelpResource {
            get {
                return ResourceManager.GetString("TotalAuthorizationCheckFailedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Authorization Requests is the total number of authorization requests received. 的本地化字符串。
        /// </summary>
        internal static string TotalAuthorizationCheckPerformedHelpResource {
            get {
                return ResourceManager.GetString("TotalAuthorizationCheckPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Security Cache Reads is the total number of security cache reads requested. 的本地化字符串。
        /// </summary>
        internal static string TotalSecurityCacheReadPerformedHelpResource {
            get {
                return ResourceManager.GetString("TotalSecurityCacheReadPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found token &quot;{1}&quot; when expecting {0} at position {2}. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedTokenMessage {
            get {
                return ResourceManager.GetString("UnexpectedTokenMessage", resourceCulture);
            }
        }
    }
}
